# Generated by Django 6.0 on 2025-12-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du logement')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité (nombre de personnes)')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField(verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('nom_client', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('nb_voyageurs', models.PositiveIntegerField(verbose_name='Nombre de voyageurs')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.logement', verbose_name='Logement réservé')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date_arrivee'],
            },
        ),
    ]
